/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Message {
    id: bigint;
    text: string;
    timestamp: Time;
    fromUser: boolean;
    requestType: {
        __kind__: "textRequest";
        textRequest: null;
    } | {
        __kind__: "imageRequest";
        imageRequest: null;
    } | {
        __kind__: "videoResponse";
        videoResponse: bigint;
    } | {
        __kind__: "videoRequest";
        videoRequest: null;
    } | {
        __kind__: "imageResponse";
        imageResponse: bigint;
    };
}
export type Time = bigint;
export interface MessageInput {
    text: string;
    fromUser: boolean;
    requestType: {
        __kind__: "textRequest";
        textRequest: null;
    } | {
        __kind__: "imageRequest";
        imageRequest: null;
    } | {
        __kind__: "videoResponse";
        videoResponse: bigint;
    } | {
        __kind__: "videoRequest";
        videoRequest: null;
    } | {
        __kind__: "imageResponse";
        imageResponse: bigint;
    };
}
export interface Conversation {
    id: string;
    title: string;
    messages: Array<Message>;
    createdAt: Time;
}
export interface backendInterface {
    addConversation(userId: Principal, title: string): Promise<void>;
    addMessage(userId: Principal, conversationId: string, messageInput: MessageInput): Promise<void>;
    clearErrorMessages(userId: Principal, conversationId: string): Promise<void>;
    deleteConversation(userId: Principal, conversationId: string): Promise<void>;
    getAllConversations(_userId: Principal): Promise<Array<Conversation>>;
    getConversation(_userId: Principal, conversationId: string): Promise<Conversation | null>;
    getLastNConversations(_userId: Principal, n: bigint): Promise<Array<Conversation>>;
    getMessagesWithNRows(conversationId: string, numRows: bigint): Promise<Array<Message>>;
    renameConversation(_userId: Principal, from: string, to: string): Promise<void>;
    setMessages(userId: Principal, conversationId: string, newMessages: Array<Message>): Promise<void>;
    titleExists(_userId: Principal, title: string): Promise<boolean>;
}
import type { Conversation as _Conversation, Message as _Message, MessageInput as _MessageInput, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addConversation(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addConversation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addConversation(arg0, arg1);
            return result;
        }
    }
    async addMessage(arg0: Principal, arg1: string, arg2: MessageInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, arg1, to_candid_MessageInput_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, arg1, to_candid_MessageInput_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async clearErrorMessages(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearErrorMessages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearErrorMessages(arg0, arg1);
            return result;
        }
    }
    async deleteConversation(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConversation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConversation(arg0, arg1);
            return result;
        }
    }
    async getAllConversations(arg0: Principal): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConversations(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConversations(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal, arg1: string): Promise<Conversation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0, arg1);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0, arg1);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastNConversations(arg0: Principal, arg1: bigint): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastNConversations(arg0, arg1);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastNConversations(arg0, arg1);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesWithNRows(arg0: string, arg1: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesWithNRows(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesWithNRows(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameConversation(arg0: Principal, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameConversation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameConversation(arg0, arg1, arg2);
            return result;
        }
    }
    async setMessages(arg0: Principal, arg1: string, arg2: Array<Message>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMessages(arg0, arg1, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMessages(arg0, arg1, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async titleExists(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.titleExists(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.titleExists(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Conversation_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Conversation]): Conversation | null {
    return value.length === 0 ? null : from_candid_Conversation_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    messages: Array<_Message>;
    createdAt: _Time;
}): {
    id: string;
    title: string;
    messages: Array<Message>;
    createdAt: Time;
} {
    return {
        id: value.id,
        title: value.title,
        messages: from_candid_vec_n7(_uploadFile, _downloadFile, value.messages),
        createdAt: value.createdAt
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    text: string;
    timestamp: _Time;
    fromUser: boolean;
    requestType: {
        textRequest: null;
    } | {
        imageRequest: null;
    } | {
        videoResponse: bigint;
    } | {
        videoRequest: null;
    } | {
        imageResponse: bigint;
    };
}): {
    id: bigint;
    text: string;
    timestamp: Time;
    fromUser: boolean;
    requestType: {
        __kind__: "textRequest";
        textRequest: null;
    } | {
        __kind__: "imageRequest";
        imageRequest: null;
    } | {
        __kind__: "videoResponse";
        videoResponse: bigint;
    } | {
        __kind__: "videoRequest";
        videoRequest: null;
    } | {
        __kind__: "imageResponse";
        imageResponse: bigint;
    };
} {
    return {
        id: value.id,
        text: value.text,
        timestamp: value.timestamp,
        fromUser: value.fromUser,
        requestType: from_candid_variant_n10(_uploadFile, _downloadFile, value.requestType)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    textRequest: null;
} | {
    imageRequest: null;
} | {
    videoResponse: bigint;
} | {
    videoRequest: null;
} | {
    imageResponse: bigint;
}): {
    __kind__: "textRequest";
    textRequest: null;
} | {
    __kind__: "imageRequest";
    imageRequest: null;
} | {
    __kind__: "videoResponse";
    videoResponse: bigint;
} | {
    __kind__: "videoRequest";
    videoRequest: null;
} | {
    __kind__: "imageResponse";
    imageResponse: bigint;
} {
    return "textRequest" in value ? {
        __kind__: "textRequest",
        textRequest: value.textRequest
    } : "imageRequest" in value ? {
        __kind__: "imageRequest",
        imageRequest: value.imageRequest
    } : "videoResponse" in value ? {
        __kind__: "videoResponse",
        videoResponse: value.videoResponse
    } : "videoRequest" in value ? {
        __kind__: "videoRequest",
        videoRequest: value.videoRequest
    } : "imageResponse" in value ? {
        __kind__: "imageResponse",
        imageResponse: value.imageResponse
    } : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n8(_uploadFile, _downloadFile, x));
}
function to_candid_MessageInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageInput): _MessageInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Message_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Message): _Message {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    text: string;
    timestamp: Time;
    fromUser: boolean;
    requestType: {
        __kind__: "textRequest";
        textRequest: null;
    } | {
        __kind__: "imageRequest";
        imageRequest: null;
    } | {
        __kind__: "videoResponse";
        videoResponse: bigint;
    } | {
        __kind__: "videoRequest";
        videoRequest: null;
    } | {
        __kind__: "imageResponse";
        imageResponse: bigint;
    };
}): {
    id: bigint;
    text: string;
    timestamp: _Time;
    fromUser: boolean;
    requestType: {
        textRequest: null;
    } | {
        imageRequest: null;
    } | {
        videoResponse: bigint;
    } | {
        videoRequest: null;
    } | {
        imageResponse: bigint;
    };
} {
    return {
        id: value.id,
        text: value.text,
        timestamp: value.timestamp,
        fromUser: value.fromUser,
        requestType: to_candid_variant_n3(_uploadFile, _downloadFile, value.requestType)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    fromUser: boolean;
    requestType: {
        __kind__: "textRequest";
        textRequest: null;
    } | {
        __kind__: "imageRequest";
        imageRequest: null;
    } | {
        __kind__: "videoResponse";
        videoResponse: bigint;
    } | {
        __kind__: "videoRequest";
        videoRequest: null;
    } | {
        __kind__: "imageResponse";
        imageResponse: bigint;
    };
}): {
    text: string;
    fromUser: boolean;
    requestType: {
        textRequest: null;
    } | {
        imageRequest: null;
    } | {
        videoResponse: bigint;
    } | {
        videoRequest: null;
    } | {
        imageResponse: bigint;
    };
} {
    return {
        text: value.text,
        fromUser: value.fromUser,
        requestType: to_candid_variant_n3(_uploadFile, _downloadFile, value.requestType)
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "textRequest";
    textRequest: null;
} | {
    __kind__: "imageRequest";
    imageRequest: null;
} | {
    __kind__: "videoResponse";
    videoResponse: bigint;
} | {
    __kind__: "videoRequest";
    videoRequest: null;
} | {
    __kind__: "imageResponse";
    imageResponse: bigint;
}): {
    textRequest: null;
} | {
    imageRequest: null;
} | {
    videoResponse: bigint;
} | {
    videoRequest: null;
} | {
    imageResponse: bigint;
} {
    return value.__kind__ === "textRequest" ? {
        textRequest: value.textRequest
    } : value.__kind__ === "imageRequest" ? {
        imageRequest: value.imageRequest
    } : value.__kind__ === "videoResponse" ? {
        videoResponse: value.videoResponse
    } : value.__kind__ === "videoRequest" ? {
        videoRequest: value.videoRequest
    } : value.__kind__ === "imageResponse" ? {
        imageResponse: value.imageResponse
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Message>): Array<_Message> {
    return value.map((x)=>to_candid_Message_n13(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
