/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Conversation {
  'id' : string,
  'title' : string,
  'messages' : Array<Message>,
  'createdAt' : Time,
}
export interface Message {
  'id' : bigint,
  'text' : string,
  'timestamp' : Time,
  'fromUser' : boolean,
  'requestType' : { 'textRequest' : null } |
    { 'imageRequest' : null } |
    { 'videoResponse' : bigint } |
    { 'videoRequest' : null } |
    { 'imageResponse' : bigint },
}
export interface MessageInput {
  'text' : string,
  'fromUser' : boolean,
  'requestType' : { 'textRequest' : null } |
    { 'imageRequest' : null } |
    { 'videoResponse' : bigint } |
    { 'videoRequest' : null } |
    { 'imageResponse' : bigint },
}
export type Time = bigint;
export interface _SERVICE {
  'addConversation' : ActorMethod<[Principal, string], undefined>,
  'addMessage' : ActorMethod<[Principal, string, MessageInput], undefined>,
  'clearErrorMessages' : ActorMethod<[Principal, string], undefined>,
  'deleteConversation' : ActorMethod<[Principal, string], undefined>,
  'getAllConversations' : ActorMethod<[Principal], Array<Conversation>>,
  'getConversation' : ActorMethod<[Principal, string], [] | [Conversation]>,
  'getLastNConversations' : ActorMethod<
    [Principal, bigint],
    Array<Conversation>
  >,
  'getMessagesWithNRows' : ActorMethod<[string, bigint], Array<Message>>,
  'renameConversation' : ActorMethod<[Principal, string, string], undefined>,
  'setMessages' : ActorMethod<[Principal, string, Array<Message>], undefined>,
  'titleExists' : ActorMethod<[Principal, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];