/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MessageInput = IDL.Record({
  'text' : IDL.Text,
  'fromUser' : IDL.Bool,
  'requestType' : IDL.Variant({
    'textRequest' : IDL.Null,
    'imageRequest' : IDL.Null,
    'videoResponse' : IDL.Nat,
    'videoRequest' : IDL.Null,
    'imageResponse' : IDL.Nat,
  }),
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : Time,
  'fromUser' : IDL.Bool,
  'requestType' : IDL.Variant({
    'textRequest' : IDL.Null,
    'imageRequest' : IDL.Null,
    'videoResponse' : IDL.Nat,
    'videoRequest' : IDL.Null,
    'imageResponse' : IDL.Nat,
  }),
});
export const Conversation = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  'addConversation' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'addMessage' : IDL.Func([IDL.Principal, IDL.Text, MessageInput], [], []),
  'clearErrorMessages' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'deleteConversation' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'getAllConversations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Conversation)],
      ['query'],
    ),
  'getConversation' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(Conversation)],
      ['query'],
    ),
  'getLastNConversations' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Vec(Conversation)],
      ['query'],
    ),
  'getMessagesWithNRows' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'renameConversation' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'setMessages' : IDL.Func([IDL.Principal, IDL.Text, IDL.Vec(Message)], [], []),
  'titleExists' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MessageInput = IDL.Record({
    'text' : IDL.Text,
    'fromUser' : IDL.Bool,
    'requestType' : IDL.Variant({
      'textRequest' : IDL.Null,
      'imageRequest' : IDL.Null,
      'videoResponse' : IDL.Nat,
      'videoRequest' : IDL.Null,
      'imageResponse' : IDL.Nat,
    }),
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : Time,
    'fromUser' : IDL.Bool,
    'requestType' : IDL.Variant({
      'textRequest' : IDL.Null,
      'imageRequest' : IDL.Null,
      'videoResponse' : IDL.Nat,
      'videoRequest' : IDL.Null,
      'imageResponse' : IDL.Nat,
    }),
  });
  const Conversation = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'createdAt' : Time,
  });
  
  return IDL.Service({
    'addConversation' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'addMessage' : IDL.Func([IDL.Principal, IDL.Text, MessageInput], [], []),
    'clearErrorMessages' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'deleteConversation' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'getAllConversations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Conversation)],
        ['query'],
      ),
    'getConversation' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'getLastNConversations' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Vec(Conversation)],
        ['query'],
      ),
    'getMessagesWithNRows' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'renameConversation' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setMessages' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Vec(Message)],
        [],
        [],
      ),
    'titleExists' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };